### ISSUE TITLE
Sections formatting not working correctly

### ISSUE THREAD

**Issue by achambery** [simbo/msteams-message-card-action#1]
Hello,

I am trying to set-up a notification that includes "section" content, however, I am encountering the following error when using the exact template provided as part of README:

![image](https://github.com/simbo/msteams-message-card-action/assets/28744847/93338e2e-e152-41d7-877a-f6b22f1db865)

Including my yaml below as well:

```
name: Microsoft Teams Notification

on: workflow_dispatch

jobs:
  teams-notification:
    name: Send Teams Notification
    runs-on: self-hosted
    steps:
      - name: 📣 Send Teams notification
        uses: simbo/msteams-message-card-action@v1.4.3
        if: always()
        continue-on-error: true
        with:
          webhook: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK }}
          title: Hello world!
          message: <p>This is my <strong>awesome message!</strong></p>
          color: ff69b4
          buttons: |
            Click here! https://whatever.com/foo/
            Or here… https://somewhere.com/bar/
          sections: |
            -
              activityTitle: David Claux
              activitySubtitle: 9/13/2016, 3:34pm
              activityImage: https://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg
              facts:
                -
                  name: "Board:"
                  value: Name of board
                -
                  name: "List:"
                  value: Name of list
                -
                  name: "Assigned to:"
                  value: (none)
                -
                  name: "Due date:"
                  value: (none)
              text: Lorem ipsum dolor sit amet
```

**Comment by simbo** [comment]
Hey @achambery,

I am very sorry, that you ran into this issue.
The documentation is not up-to-date and misleading. I need to fix that soon.

If you change your activity definition as follows, it should work as expected:

```
  sections: |
    -
      activity:
        title: David Claux
        subtitle: 9/13/2016, 3:34pm
        image: https://connectorsdemo.azurewebsites.net/images/MSC12_Oscar_002.jpg
```

The input format follows the interface of the underlying library function `createMessageCardPayload(…)` ([see documentation](https://github.com/simbo/msteams-message-cards#createmessagecardpayload)).

Now that you ran into this issue, I see that the input format should either be closer to the original data format of message cards or simply also support native data objects. That would make options values more tolerant and failsafe. I'll try to implement/change this.

Please let me know if it's working for you now.

### ToDo

- [ ] fix docs about activity data
- [ ] improve payload options
