### ISSUE TITLE
Unicode characters with "New" Microsoft Teams in title

### ISSUE THREAD

**Issue by futureviperowner** [simbo/msteams-message-card-action#2]
I recently updated to the new Microsoft Teams and noticed that Unicode characters in my Teams notifications are no longer displaying properly.  I've only tested them in the notification title, not the body.

This could be a Teams issue, but I figured it could also be caused by changes to the Teams API that the action might need to adopt.

```yaml
      - name: Teams Notification
        uses: simbo/msteams-message-card-action@v1
        with:
          webhook: ${{ secrets.TEAMS_WEBHOOK_URL_DEPLOYMENT_NOTIFICATIONS }}
          color: 28a745
          title: 🎉 Deployment Successful!
          message: |
            Service: <strong>${{ fromJSON(github.event.inputs.json).resourceName }}:${{ fromJSON(github.event.inputs.json).resourceVersion }}</strong><br />
            Environment: <strong>${{ fromJSON(github.event.inputs.json).environment }} (${{ fromJSON(github.event.inputs.json).location }})</strong><br />
            Deployed Release: <strong>${{ env.DEPLOYMENT_TRIGGER_SUMMARY }}</strong><br />
            Developers: <strong>${{ env.DEPLOYMENT_PR_AUTHOR }}</strong><br />
```

![image](https://github.com/simbo/msteams-message-card-action/assets/840944/591590f6-33c9-4c69-8e63-415dc4115594)
